spring:
  config:
    import: 'optional:consul:'
  application:
    name: ingestion-service
  cloud:
    service-registry:
      auto-registration:
        enabled: true
    consul:
      enabled: true
      host: 127.0.0.1
      port: 8500
      config:
        enabled: true
      discovery:
        enabled: true
        port: ${api.port}
        health-check-interval: 30s
        health-check-url: "http://localhost:${api.port}/health/check"
        instance-id: ${spring.application.name}-${random.value}

api:
  port: 8081
